version: "3.7"

services:
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]

  app_server:
    build: ./server
    links:
      - redis
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - REDIS_URL=${REDIS_URL}

  app_client:
    build: ./client
    links:
      - app_server
    ports:
      - ${REACT_APP_CLIENT_PORT}:${REACT_APP_ORIGINAL_PORT}
    environment:
      - REACT_APP_API_ENDPOINT=${REACT_APP_API_ENDPOINT}
    stdin_open: true
