export default {
  CHANGE_NEW_URL_FORM_VALUE: "CHANGE_NEW_URL_FORM_VALUE",

  SUBMIT_NEW_URL: "SUBMIT_NEW_URL",
  SUBMIT_NEW_URL_SUCCESS: "SUBMIT_NEW_URL_SUCCESS",
  SUBMIT_NEW_URL_FAIL: "SUBMIT_NEW_URL_FAIL",

  GET_ALL_URLS: "GET_ALL_URLS",
  GET_ALL_URLS_SUCCESS: "GET_ALL_URLS_SUCCESS",
  GET_ALL_URLS_FAIL: "GET_ALL_URLS_FAIL",
};
